services:
  - type: web
    name: brown-course-catalog-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: brown-course-catalog-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3

  - type: web
    name: brown-course-catalog-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://brown-course-catalog-backend.onrender.com
    autoDeploy: true

databases:
  - name: brown-course-catalog-db
    databaseName: brown_course_catalog
    user: brown_course_catalog_user
    plan: starter 