services:
  # Backend API Service
  - type: web
    name: brown-course-catalog-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run setup-db
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  # Frontend Web Service
  - type: web
    name: brown-course-catalog-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: VITE_API_URL
        value: https://brown-course-catalog.onrender.com 