services:
  # Backend API Service
  - type: web
    name: brown-course-catalog-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://bruno_course_catalog_db_user:CzP7vLlYpGUmsfl1yE42SYeSVd2ejDJx@dpg-d2ntiher433s73alehrg-a.ohio-postgres.render.com/bruno_course_catalog_db?sslmode=require
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  # Frontend Static Site
  - type: web
    name: brown-course-catalog-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: VITE_API_URL
        value: https://brown-course-catalog-backend.onrender.com 