-- Brown University Undergraduate Course Catalog
-- Based on official course offerings for 2024-2025 academic year
-- This replaces the sample courses with real Brown University courses

-- Clear existing courses
DELETE FROM courses;

INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('AFRI 0090', 'An Introduction to Africana Studies', 'This course introduces students to the vibrant and contested field of Africana Studies by critically exploring and analyzing the links and disjunctures in the cultural, political, and intellectual practices and experiences of people of African descent throughout the African diaspora. Beginning with a critical overview of the history, theoretical orientations, and multiple methodological strategies of the discipline, the course is divided into three thematic units that examine intellectuals, politics, and movements; identity construction and formation; and literary, cultural, and aesthetic theories and practices in the African diaspora.', 'TR', '13:00:00', '14:20:00', 'Salomon Center 003', 'Prof. Francoise Hamlin'),
('AFRI 0300', 'Performing Ethnography and the Politics of Culture', 'This course introduces students to the practice of fieldwork observation (ethnography) as a research method to investigate how culture is enacted and communities are formed and sustained. Regular opportunities to observe and participate in Black cultural events and institutions in and around Providence. Opportunities to sample local cuisines and to visit community gardens, religious institutions, and other cultural sites will develop students'' capacity to conduct research. These experiences, combined with the course readings and other assignments, will teach students how to analyze and disseminate their findings in writing and through a final creative project.', 'M', '15:00:00', '17:30:00', 'Churchill House 008', 'Prof. Lisa Biggs'),
('AFRI 0410', 'After the Uprisings: Abolition and Black Studies', 'This small, discussion-based seminar will examine the concept of “abolition” and its relationship to Black Studies. In the aftermath of the uprisings of 2020, abolition has become part of popular discourse in ways hardly imagined by some of its theorists and practitioners. The framework is most often aimed at carceral structures such as police, prisons, and surveillance, yet some interpretations of abolition take aim at the state, borders, and even the world. This seminar will explore the varied discourses of abolition and invite students to wrestle with the theoretical and practical difficulties the framework is confronted with, such as questions of law, politics, gender, and temporality. A key site of inquiry will be the methods of struggle proposed to get from the present to the anticipated abolitionist future. What “pathways to abolition” are prioritized, while others fall off the table?
', 'T', '16:00:00', '18:30:00', 'Churchill House 008', 'Prof. Justin Lang'),
('AFRI 0420', 'Cannabis Legalization: Race, Education, and Policing', 'This course investigates issues related to policing, race, education and the legalization of cannabis. It examines Silicon Valley’s innovations, foreign and domestic venture capital funding, and the “Big Cannabis” industry. We also explore race-related disparities in policies related to the selling and policing of cannabis, and the economic impact cannabis legalization has had on funding for public education and public schools. We will also explore various community and policy strategies to address race-based arrest and incarceration rates pre-legalization, race and gender-based differences in licensing programs for cannabis entrepreneurs, and the health impacts of cannabis processing plant placements which tend to be heavily clustered in poor, urban communities of color. We will invite local elected officials, nonprofit groups working on the topics, dispensary founders from the local area, and hopefully, cannabis funders and entrepreneurs to provide us with first-hand perspectives.', 'MWF', '9:00:00', '9:50:00', 'List Art Center 120', 'Prof. Noliwe Rooks'),
('AFRI 0670', 'Global Black Radicalism', 'The decade from the mid-Sixties until the mid-Seventies witnessed the rise of Black Radicalism as a global phenomenon. The emergence of Black Power in the US, Brazil and the Caribbean, the consolidation of liberation struggles in Portuguese Africa and the rise of a Black Consciousness trend in Apartheid South Africa all represent key moments. What led young activists to embrace “Black Power?” What led to the emergence of Marxist movements in Portuguese Africa? What events in the Caribbean gave ascendancy to radical tendencies? And what forces contributed to the decline of these movements? This course seeks to answer these questions.
', 'W', '15:00:00', '17:30:00', 'Churchill House 008', 'Prof. Brian Meeks'),
('AFRI 1112', 'What''s Popping: The Contemporary Black Theatre Workshop', 'Open to all Brown students, this course introduces students to contemporary (post-1980) Black theatre history, theory, and artistic practice. Students will read, analyze and interpret a range of influential plays such as What to Send Up When It Goes Down, Hurt Village, Twilight, Topdog/Underdog, Choir Boy, Bootycandy, Diary of a Mad Black Woman, and Fences. Course work includes opportunities to perform scenes and monologues, see live theatre in and around Providence, and devise original performance works through in-class writing, movement, and improv theatre exercises. The semester culminates in an Artists Salon featuring students'' work. No previous acting, improv, movement, directing, playwriting or Black theatre experience required. No prereqs. All are welcome.
', 'TR', '10:30:00', '11:50:00', 'Churchill House BASSPA AUD', 'Prof. Lisa Biggs');

-- Applied Mathematics Department
INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('APMA 0160', 'Introduction to Scientific Computing', 'For students in any discipline that may involve numerical computations. Includes instruction for programming in MATLAB. Applications discussed include solution of linear equations (with vectors and matrices) and nonlinear equations (by bisection, iteration, and Newton''s method), interpolation, and curve-fitting, difference equations, iterated maps, numerical differentiation and integration, and differential equations. Prerequisites: MATH 0100 or equivalent.
', 'TR', '9:00:00', '10:20:00', 'Friedman Hall 202', 'Prof. Rami Marsi'),
('APMA 0260', 'Linear Algebra and Multivariable Calculus for Applied Mathematicians', 'This one-semester course provides an integrated introduction to multi-variable calculus and linear algebra. Students will develop a strong foundation in mathematical concepts and techniques essential for the applied mathematics concentration.
', 'MWF', '14:00:00', '14:50:00', '67 George Street 104', 'Prof. Peyam Tabrizian'),
('APMA 0350', 'Applied Ordinary Differential Equations', 'This course provides a comprehensive introduction to ordinary differential equations and their applications. During the course, we will see how applied mathematicians use ordinary differential equations to solve practical applications, from understanding the underlying problem, creating a differential-equations model, solving it using analytical, numerical, or qualitative methods, and interpreting the findings in terms of the original problem. This course is geared towards methods for solving ordinary differential equations rather than the underlying theoretical foundations. Prerequisites: MATH 0100 or equivalent; knowledge of matrix-vector operations, determinants, and linear systems. Linear algebra is strongly recommended as a prerequisite or corequisite.', 'MWF', '12:00:00', '12:50:00', 'MacMillan Hall 117', 'Peyam Tabrizian'),
('APMA 0355', 'Applied Ordinary Differential Equations with Theory', 'This course provides a comprehensive introduction to ordinary differential equations, their applications, and their theoretical underpinnings. During the course, we will see how applied mathematicians use ordinary differential equations to solve practical applications, from understanding the underlying problem, creating a differential-equations model, solving it using analytical, numerical, or qualitative methods, and interpreting the findings in terms of the original problem. We will also learn about the underlying rigorous theoretical foundations of differential equations and the mathematical formalism used to establish this theory. Prerequisites: Multivariable calculus; Linear algebra.', 'MWF', '13:00:00', '13:50:00', 'Barus & Holley 168', 'Prof. Bjorn Sandstede'),
('APMA 0360', 'Applied Partial Differential Equations I', 'This course provides an introduction to partial differential equations and their applications, with an emphasis on techniques for solving PDEs rather than theory. We will learn how to use partial differential equations to solve problems that arise in practical applications by formulating questions about a real-world problem, creating a partial differential equation model that can help answer these questions, solving the resulting system using analytical, numerical, and qualitative methods, and interpreting the results in terms of the original application. Topics include the four fundamental PDEs (transport, wave, heat, and Laplace equations), solution techniques (Fourier transform, energy methods, separation of variables, maximum principles), and example applications. Prerequisites: Multivariable calculus; APMA 0350 or equivalent.', 'MWF', '12:00:00', '12:50:00', 'Smith-Buonanno Hall 106', 'Prof. Yan Guo'),
('APMA 0650', 'Introduction to Probability and Statistics', 'A first course in probability and statistics without calculus. Topics include data fluency, probability spaces, discrete and continuous random variables, expected values, law of large numbers, central limit theorem, point estimation, confidence intervals, hypothesis testing, measures of association, linear regression. Examples and applications from the popular press and the life, social and physical sciences.', 'MWF', '10:00:00', '10:50:00', 'Kassar House FOX', 'Prof. Amalia Culiuc'),
('APMA 1000', 'Introduction to Mathematical Proofs', 'This course serves as an introduction to mathematical writing, with a focus on building practical skills for proof writing. The central theme of the course is constructing, analyzing, and understanding mathematical arguments. The course will cover the fundamental proof techniques, including direct proofs, contradiction, contrapositive, existence and uniqueness, induction, and epsilon-delta.', 'MWF', '9:00:00', '9:50:00', 'Barus & Holley 160', 'Prof. Mira Gordin'),
('APMA 1080', 'Inference in Genomics and Molecular Biology', 'This course is an introduction to the probabilistic and statistical models that have found widespread use in genomics and molecular biology. The emphasis is on foundational models and ideas rather than practical application. Likely topics include Markov chains, hidden Markov models, directed graphical models, mixture models, linear regression, regularization, dimensionality reduction, clustering, Bayesian inference, and multiple hypothesis testing. Examples will focus on the connection to genomics and molecular biology, but all of these tools have found widespread use in a variety of disciplines. Mathematical and computational exercises will reinforce the topics presented in lecture. Prerequisites: Multivariable calculus; Linear algebra; Computer programming; APMA 1655 or equivalent.', 'MWF', '10:00:00', '10:50:00', 'Friedman Hall 108', 'Prof. Kristina Mallory'),
('APMA 1170', 'Introduction to Computational Linear Algebra', 'Focuses on fundamental algorithms in computational linear algebra with relevance to all science concentrators. Basic linear algebra and matrix decompositions (Cholesky, LU, QR, etc.), round-off errors and numerical analysis of errors and convergence. Iterative methods and conjugate gradient techniques. Computation of eigenvalues and eigenvectors, and an introduction to least squares methods. Prerequisites: Multivariable calculus; Linear algebra. Experience with a programming language is strongly recommended.', 'MWF', '9:00:00', '9:50:00', 'Friedman Hall 101', 'Prof. Varun Khurana'),
('APMA 1210', 'Operations Research: Deterministic Models', 'An introduction to the basic mathematical ideas and computational methods of optimizing allocation of effort or resources, with or without constraints. Linear programming, network models, dynamic programming, and integer programming. Prerequisites: Multivariable calculus; Linear algebra; Computer programming.', 'TR', '10:30:00', '11:50:00', 'Barus & Holley 166', 'Prof. Caroline Klivans');
-- Computer Science Department
INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('CSCI 0150', 'Introduction to Object-Oriented Programming and Computer Science', 'Introduction to programming in Java, object-oriented design, and fundamental computer science concepts', 'MWF', '10:00:00', '10:50:00', 'CIT 165', 'Prof. Sarah Chen');

-- Mathematics Department
INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('MATH 0100', 'Introductory Calculus, Part I', 'Single variable calculus with applications to science and engineering', 'MWF', '09:00:00', '09:50:00', 'Kassar 105', 'Prof. William Clark');

-- Economics Department
INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('ECON 0110', 'Principles of Economics', 'Introduction to microeconomics and macroeconomics principles', 'MWF', '13:00:00', '13:50:00', 'Wilson 101', 'Prof. Ashley Collins');

-- Physics Department
INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('PHYS 0030', 'Basic Physics', 'Mechanics, thermodynamics, and wave phenomena for non-science majors', 'MWF', '15:00:00', '15:50:00', 'Barus 166', 'Prof. Noah Price');

-- Chemistry Department
INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('CHEM 0100', 'Introductory Chemistry', 'Fundamental principles of chemistry for non-science majors', 'MWF', '10:00:00', '10:50:00', 'Metcalf 101', 'Prof. Rowan Powell');

-- Biology Department
INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('BIOL 0200', 'The Foundation of Living Systems', 'Introduction to biology, cell biology, and genetics', 'MWF', '10:00:00', '10:50:00', 'Sidney Frank 220', 'Prof. Juniper Adams');

-- Psychology Department
INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('PSYC 0010', 'Introduction to Psychology', 'Introduction to psychological science and research methods', 'MWF', '10:00:00', '10:50:00', 'Metcalf 101', 'Prof. Lily Chen');

-- History Department
INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('HIST 0100', 'Introduction to History', 'Introduction to historical thinking and research methods', 'MWF', '10:00:00', '10:50:00', 'Pembroke 305', 'Prof. River Chen');

-- English Department
INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('ENGL 0100', 'Introduction to Literary Studies', 'Introduction to literary analysis and critical thinking', 'MWF', '10:00:00', '10:50:00', 'Pembroke 305', 'Prof. Sky Chen');

-- Philosophy Department
INSERT INTO courses (code, name, description, days, start_time, end_time, location, professor) VALUES
('PHIL 0100', 'Introduction to Philosophy', 'Introduction to philosophical thinking and major philosophical questions', 'MWF', '10:00:00', '10:50:00', 'Pembroke 305', 'Prof. Star Chen');


